pipeline {
    agent any
    stages{
        stage('Front clone'){
            steps{
                git branch: 'FE', credentialsId: 'GitLab-Last', url: 'https://lab.ssafy.com/s10-final/S10P31D203.git'
            }
        }

        stage('Docker front image build') {
            steps {
                dir('whoru-frontend') {
                    sh "docker stop frontend || true && docker rm frontend || true"
                    sh 'docker rmi frontend || true'
                    sh 'docker build -t frontend .' 
                }
            }
        }

        stage('Docker front container run && connect network') {
            steps {
                dir('whoru-frontend') {
                    sh 'docker run -d -v /config/front/d203front.conf:/etc/nginx/conf.d/d203front.conf -p 3000:3000 --net whoru --name frontend frontend'
                }
            }
        }
    }
}
